In [1]:
import os
import sys
import talib as ta
syspath = os.path.split(os.path.abspath("."))[0]
sys.path.append(syspath)
import univ3api.simulation as sim
import univ3api.utils as utils
import importlib
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
# run if simulation file is updated
importlib.reload(sim)

HOST = "mongodb://172.16.11.81:27017/ETHDATA"
source = sim.DataUtilMongoDB(HOST)

from datetime import datetime
import time
d1 = datetime(2021,5,10,9)
d2 = datetime(2021,11,10,9)
t1 = int(time.mktime(d1.timetuple()))
t2 = int(time.mktime(d2.timetuple()))
# print(d1.timetuple())
# print(time.mktime(d1.timetuple()))
# print(int(time.mktime(d1.timetuple())))
# swapdata = source.swap_by_time("SWAP_WETH_USDT_3000", t1, t2)
swapdata = source.swap_by_time("SWAP_WBTC_WETH_3000", t1, t2)
swapdata.tail()
pricedata = swapdata[["timestamp", "sqrtPriceX96"]]
# pricedata["price"] = pricedata["sqrtPriceX96"].apply(utils.PriceConverter(18, 6).x96_to_price)
pricedata["price"] = pricedata["sqrtPriceX96"].apply(utils.PriceConverter(8, 18).x96_to_price)

In [2]:
pricedata.tail()

        timestamp                         sqrtPriceX96      price
48852  1636435773  29838382263891094853397020984797412  14.183760
48853  1636435798  29830238196962177663795291495427951  14.176019
48854  1636436219  29829209673960410593094947881286270  14.175041
48855  1636437629  29824500165996756564070629748592845  14.170565
48856  1636437664  29810996843813421171183418482833476  14.157737

In [3]:
swapdata.tail()

,transactionHash,logIndex,transactionIndex,blockNumber,recipient,amount0,amount1,sqrtPriceX96,liquidity,tick,timestamp
48852,0xf00e1f5f129b87e82870ff45fb66085c0b3e4e2e3599...,531,307,13580335,0x56178a0d5F301bAf6CF3e1Cd53d9863437345Bf9,296737949,-41968570803314817714,29838382263891094853397020984797412,749672491973455435,256792,1636435773
48853,0xbdea0bbb10d3f21466ca3566a8a27f20c05aee96f47a...,5,0,13580336,0xDFee68a9aDb981CD08699891A11CaBE10f25ec44,545086393,-77060766722953279203,29830238196962177663795291495427951,749672491973455435,256786,1636435798
48854,0x7ed53474ddaed2a7a7f95eeb7bc93450b07d644d6a3f...,142,107,13580370,0xDef1C0ded9bec7F1a1670819833240f027b25EfF,68860718,-9732087395664601204,29829209673960410593094947881286270,749672491973455435,256786,1636436219
48855,0x5e5e128cf69543dba42c5be10d2bbdb677869711c5c1...,108,49,13580470,0x56178a0d5F301bAf6CF3e1Cd53d9863437345Bf9,315367268,-44562292738339071497,29824500165996756564070629748592845,749672491973455435,256783,1636437629
48856,0xd2fd8d404863da141904b05d0d4cb8aa9b9855ae2ae3...,40,7,13580474,0xe0a9efE32985cC306255b395a1bd06D21ccEAd42,904788263,-127771096411316051792,29810996843813421171183418482833476,749672491973455435,256773,1636437664

In [4]:
pricedata['datetime'] = pd.to_datetime(pricedata['timestamp'],unit='s')
priceDt = pricedata.set_index('datetime')
priceDt['date'] = list(map(lambda d: d.date(), priceDt.index))
priceDt

,timestamp,sqrtPriceX96,price,date
datetime,,,,
2021-05-10 01:00:57,1620608457,30685129890900272086470739815588235,15.000190,2021-05-10
2021-05-10 01:00:57,1620608457,30709533659969384051347723595723166,15.024059,2021-05-10
2021-05-10 01:03:12,1620608592,30705863068469425277565093729731105,15.020468,2021-05-10
2021-05-10 01:04:43,1620608683,30724919029063427727612188810824282,15.039117,2021-05-10
2021-05-10 01:05:15,1620608715,30722150531496348621299112840911173,15.036406,2021-05-10
...,...,...,...,...
2021-11-09 05:29:33,1636435773,29838382263891094853397020984797412,14.183760,2021-11-09
2021-11-09 05:29:58,1636435798,29830238196962177663795291495427951,14.176019,2021-11-09
2021-11-09 05:36:59,1636436219,29829209673960410593094947881286270,14.175041,2021-11-09
2021-11-09 06:00:29,1636437629,29824500165996756564070629748592845,14.170565,2021-11-09
2021-11-09 06:01:04,1636437664,29810996843813421171183418482833476,14.157737,2021-11-09

In [5]:
UDP60 = pd.read_csv('../data/symbolsSig/UDP60.csv',index_col=0)
MA = pd.read_csv('../data/symbolsSig/MA60.csv',index_col=0)
# MA60 = pd.read_csv('../data/symbolsSig/MA60.csv',index_col=0)
UDP60.dropna(axis = 0,how='any',inplace=True)
UDP60.index = pd.to_datetime(UDP60.index)
udpInd = UDP60.index.tolist()
MA.dropna(axis = 0,how='any',inplace=True)
MA.index = pd.to_datetime(MA.index)
maInd = MA.index.tolist()
# print(type(udpInd[0]))
# str(udpInd[0])[:-6]
strudpInd = [str(ind)[:-6] for ind in udpInd]
strmaInd = [str(ind)[:-6] for ind in maInd]
UDP60.index  = strudpInd
MA.index = strmaInd
# UDP60
MA.columns = ['btcCLOSEoverMA','ethCLOSEoverMA']

In [6]:
udpDict = dict(UDP60['udp60'])
maBTCDict = dict(MA['btcCLOSEoverMA'])
maETHDict = dict(MA['ethCLOSEoverMA'])
udpList = []
maBTCList = []
maETHList =  []
for i, v in priceDt.iterrows():
    k =str(pd.to_datetime(v['date']))
    udpList.append(udpDict[k])
    maBTCList.append(maBTCDict[k])
    maETHList.append(maETHDict[k])
print(f'len of udpList:{len(udpList)}')
priceDt['udp'] = udpList
print(f'len of maBTCList:{len(maBTCList)}')
print(f'len of maETHList:{len(maETHList)}')
priceDt['btcCLOSEoverMA'] = maBTCList
priceDt['ethCLOSEoverMA'] = maETHList

len of udpList:48857
len of maBTCList:48857
len of maETHList:48857

In [7]:
priceDt

,timestamp,sqrtPriceX96,price,date,udp,btcCLOSEoverMA,ethCLOSEoverMA
datetime,,,,,,,
2021-05-10 01:00:57,1620608457,30685129890900272086470739815588235,15.000190,2021-05-10,0.6,False,True
2021-05-10 01:00:57,1620608457,30709533659969384051347723595723166,15.024059,2021-05-10,0.6,False,True
2021-05-10 01:03:12,1620608592,30705863068469425277565093729731105,15.020468,2021-05-10,0.6,False,True
2021-05-10 01:04:43,1620608683,30724919029063427727612188810824282,15.039117,2021-05-10,0.6,False,True
2021-05-10 01:05:15,1620608715,30722150531496348621299112840911173,15.036406,2021-05-10,0.6,False,True
...,...,...,...,...,...,...,...
2021-11-09 05:29:33,1636435773,29838382263891094853397020984797412,14.183760,2021-11-09,1.0,True,True
2021-11-09 05:29:58,1636435798,29830238196962177663795291495427951,14.176019,2021-11-09,1.0,True,True
2021-11-09 05:36:59,1636436219,29829209673960410593094947881286270,14.175041,2021-11-09,1.0,True,True
2021-11-09 06:00:29,1636437629,29824500165996756564070629748592845,14.170565,2021-11-09,1.0,True,True
2021-11-09 06:01:04,1636437664,29810996843813421171183418482833476,14.157737,2021-11-09,1.0,True,True